### ISSUE TITLE
Decoding of ::: fails

### ISSUE THREAD

**Issue by ErikHellman** [patrikhson/base45#3]
There seems to be a bug that happens when decoding the string `:::`, and probably other combinations as well.

Tried the following code and it gives the wrong result:
```
decodedString := base45Decode(":::")
encodedString := base45Encode(decodedString)
fmt.Println("Decoded string:", len(decodedString), decodedString)
fmt.Println("Encoded string:", len(encodedString), encodedString)
```

The output of the encoded string should be `:::` but this is the output instead:

```
Decoded string: 4 ÅÃ
Encoded string: 3 UXO
```

**Comment by ErikHellman** [comment]
I think I found a way to catch bad base45 as input in my Kotlin version. 

https://github.com/ErikHellman/base45-kotlin/blob/43a2f6958b136a42a1261fd822a3aca1f4c90553/src/main/kotlin/se/hellsoft/base45/Base45.kt#L52

**Comment by patrikhson** [comment]
The first byte can not be ":" in the value to decode. I.e. not all combination of characters from the alphabet are valid. I should have a catch for that.
