### ISSUE TITLE
Rationale

### ISSUE THREAD

**Issue by ypiguet-epfl** [patrikhson/base45#4]
A rationale for the existence of Base45 would be welcome in the specification. To store binary data in a QR-code, the most obvious choice is bytes. If the problem is scanners which expect text, an initial `'\0'` should be fine.

**Comment by patrikhson** [comment]
You can not store bytes in a QR-code. You can only store characters of a specific encoding, and the most efficient is alphanumeric which is exactly the 45 characters selected for this encoding.

But yes, obviously this is not clear in the draft. Expect better text.

**Comment by ypiguet-epfl** [comment]
Per ISO/IEC 18004:2000 section 8.3.4 (8-bit Byte Mode), yes you can. Be it an encoding for JIS X 0201, we don't have to care because it's stated _character values 00<sub>HEX</sub> to FF<sub>HEX</sub>_. _In this mode data is encoded at a density of 8 bits/character_.

So even if QR-code were only for text (it isn't obvious to me but maybe I haven't read the ISO reference carefully enough), Base45 is an encoding for binary data which uses 8.25 bits per byte (3 characters for 2 bytes with Base45, 11 bits for 2 characters with QR-code Alphanumeric Mode), while 8-bit Bytes Mode could be a much more straightforward "encoding" which would use 8 bits per byte.

**Comment by patrikhson** [comment]
What they call "byte mode" is in reality a character mode as well, and the characters are recommended to be interpreted as ISO-8859-1 or UTF-8. This implies a decoder might very well have issues with various byte values as the mode is not in reality binary. Aztec on the other hand do have a (true) binary mode, and many of us wanted Aztec encoding and not QR, but in the discussions more people wanted QR than Aztec.
